This is makeindex, version 2.15 [TeX Live 2015] (kpathsea + Thai support).
Scanning style file /Users/wendellpbarreto/Projects/tcc/.texpadtmp/Proposta-TCC.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file /Users/wendellpbarreto/Projects/tcc/.texpadtmp/Proposta-TCC.acn...done (0 entries accepted, 0 rejected).
Nothing written in /Users/wendellpbarreto/Projects/tcc/.texpadtmp/Proposta-TCC.acr.
Transcript written in /Users/wendellpbarreto/Projects/tcc/.texpadtmp/Proposta-TCC.alg.
